### ISSUE TITLE
Build does not work

### ISSUE THREAD

**Issue by arantius** [yuliskov/SmartTubeNext#20]
First, the build instructions fail to mention the Android SDK dependency.  (Sort of a "duh", but a pain.)  Once I resolved that, I ran the build instructions and got:

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':smarttubetv:buildStbetaDebugPreBundle'.
> Could not resolve all task dependencies for configuration ':smarttubetv:stbetaDebugRuntimeClasspath'.
   > Could not find com.zlc.glide:webpdecoder:2.0.4.9.0.
...
```

I found `SharedModules/constants.gradle:    glideVersion = '4.9.0'` and (https://github.com/zjupure/GlideWebpDecoder#dependency-integration) "If your project use glide version below 4.10.0, you can only use webpdecoder 1.6 version or below."  So I patched it to version 1.6, tried again, and:

```
* What went wrong:
Execution failed for task ':smarttubetv:processStbetaDebugGoogleServices'.
> File google-services.json is missing. The Google Services Plugin cannot function without it.
```

So I have to define a Firebase project?  Then I have to do it again because I didn't give the right package name.  Then:

```
> Task :smarttubetv:processStbetaDebugGoogleServices
Parsing json file: C:\cygwin\home\t-bone\SmartTubeNext\smarttubetv\google-services.json

> Task :sharedutils:compileDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':sharedutils:compileDebugJavaWithJavac'.
> Could not find tools.jar. Please check that C:\Program Files\Java\jre1.8.0_261 contains a valid JDK installation.
```

Sigh.  I've got a JRE but not a JDK installed.  Install that.  Now I've just got:

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not initialize class org.codehaus.groovy.runtime.InvokerHelper
```

Ugh, I installed the wrong JDK (nothing said what was the right one).  Uninstall, try again...  Finally.  It took over an hour but I completed the build.

... but where is the output?  I don't have anything to install and run?

Maybe I need to run `./gradlew build` to get something useful?  But it dies on (untranslated string) lint errors!  So try `./gradlew build -x lint`?

```
...
> Task :common:compileStorigDebugJavaWithJavac FAILED
C:\cygwin\home\t-bone\SmartTubeNext\common\src\main\java\com\liskovsoft\smartyoutubetv2\common\app\models\update\AppUpdateManager.java:5: error: package com.liskovsoft.appupdatechecker2 does not exist
import com.liskovsoft.appupdatechecker2.AppUpdateChecker;
...
\SmartTubeNext\common\src\main\java\com\liskovsoft\smartyoutubetv2\common\app\models\update\AppUpdateManager.java:77: error: method does not override or implement a method from a supertype
    @Override
    ^
...
```

So remove those.  Then

```
> Task :common:compileStorigDebugJavaWithJavac FAILED
C:\cygwin\home\t-bone\SmartTubeNext\common\src\main\java\com\liskovsoft\smartyoutubetv2\common\app\models\update\AppUpdateManager.java:5: error: package com.liskovsoft.appupdatechecker2 does not exist
import com.liskovsoft.appupdatechecker2.AppUpdateChecker;
                                       ^
```

Can you please just publish an APK?

**Comment by foreveryoungforty** [comment]
Hello,

See main page.... life can be so simple 🙂
https://github.com/yuliskov/SmartYouTubeTV/releases/download/beta/smarttube_beta.apk

**Comment by arantius** [comment]
Yep, managed to overlook that.  I thought I knew how GitHub worked; why is there nothing linked from https://github.com/yuliskov/SmartTubeNext/releases/ ?

(That said, it's still hard to build this ...)

**Comment by ankuzan-github** [comment]
It would be great to make the project build out of the box. Yesterday I spent a couple hours resolving all issues.

**Comment by mo123** [comment]
Anyone managed to build successfully?

The latest error I get is
> Task :common:compileStbetaDebugJavaWithJavac FAILED
/SmartTubeNext/common/src/main/java/com/liskovsoft/smartyoutubetv2/common/app/models/update/AppUpdateManager.java:73: error: cannot find symbol
        }, mUpdateChecker.isUpdateCheckEnabled()));
                         ^
  symbol:   method isUpdateCheckEnabled()
  location: variable mUpdateChecker of type AppUpdateChecker
/SmartTubeNext/common/src/main/java/com/liskovsoft/smartyoutubetv2/common/app/presenters/settings/AboutPresenter.java:55: error: cannot find symbol
        }, mUpdateChecker.isUpdateCheckEnabled()));
                         ^
  symbol:   method isUpdateCheckEnabled()
  location: variable mUpdateChecker of type AppUpdateChecker
2 errors

**Comment by aouamed** [comment]
build on ubuntu 20.04...ERROR

SmartTubeNext/smarttubetv/src/main/java/com/liskovsoft/smartyoutubetv2/tv/ui/playback/other/StoryBoardSeekDataProvider.java:10: error: class StoryboardSeekDataProvider is public, should be declared in a file named StoryboardSeekDataProvider.java
public class StoryboardSeekDataProvider extends PlaybackSeekDataProvider {
       ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':smarttubetv:compileStorigDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.4.1/userguide/command_line_interface.html#sec:command_line_warnings

**Comment by NihatO** [comment]
The same error still occurs with the actual code. (Build on Windows x64) 
Has anybody found a solution?

> build on ubuntu 20.04...ERROR
> 
> SmartTubeNext/smarttubetv/src/main/java/com/liskovsoft/smartyoutubetv2/tv/ui/playback/other/StoryBoardSeekDataProvider.java:10: error: class StoryboardSeekDataProvider is public, should be declared in a file named StoryboardSeekDataProvider.java
> public class StoryboardSeekDataProvider extends PlaybackSeekDataProvider {
> ^
> Note: Some input files use or override a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
> Note: Some input files use unchecked or unsafe operations.
> Note: Recompile with -Xlint:unchecked for details.
> 1 error
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
>   Execution failed for task ':smarttubetv:compileStorigDebugJavaWithJavac'.
> 
> > Compilation failed; see the compiler error output for details.
> 
> * Try:
>   Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> * Get more help at https://help.gradle.org
> 
> Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
> Use '--warning-mode all' to show the individual deprecation warnings.
> See https://docs.gradle.org/5.4.1/userguide/command_line_interface.html#sec:command_line_warnings

**Comment by KumarVelu** [comment]
I am facing the same problem guys, why is this not highlighted, how are others able to build it and run.

**Comment by bannmann** [comment]
I attempted to build SmartTube today. It failed due to 7 (IIRC) warnings from the linter and several broken tests.

Once I disabled linter and tests entirely, the build succeeded. I didn't check whether the application would run, though.

Anyway, in case it helps anyone, here's the command that worked:

```
gradlew build -x lint -x test
```

This is on Windows; in other OSes it would probably be:

```
./gradlew build -x lint -x test
```

Note: make sure that the `JAVA_HOME` variable points to a JDK 14 and the system PATH is set up to point to that as well. Use `javac -version` and `java -version` to verify this.
